baseURL = "https://68656c6c.com"
languageCode = "en-us"
title = "Blog"
theme = "dead-simple"
enableGitInfo = "true"

[menu]
  [menu.main]
    name = "<u>H</u>ome"
    url = "/"
    weight = "1"

  [menu.main]
    name = "<u>T</u>ags"
    url = "https://68656c6c.com/tags"
    weight = "3"

[params]
  description = "Blog"
  noSearch = "false"

[markup]
  [markup.highlight]
    codeFences = "true"
    style = "bw"
    lineNumbersInTable = "false"
    noClasses = "false"
  [markup.goldmark.renderer]
    unsafe = "true"

[outputs]
  home = ['html', 'rss', 'json']
  page = ['html']

[module]
  [module.imports]
    path = "github.com/barklan/hugo-dead-simple"